root = "."
tmp_dir = "tmp"

[build]
# 只监视这些目录的文件变化
include_dir = ["cmd", "internal", "web"]
# 忽略这些目录
exclude_dir = ["tmp", "vendor"]
# 监视这些扩展名的文件
include_ext = ["go", "html", "css", "js"]
# 忽略这些文件
exclude_file = []
# 主程序入口
cmd = "go build -o ./tmp/main ./cmd/main.go"
# 二进制文件路径
bin = "./tmp/main"
# 自定义参数
args_bin = []
# 延迟时间（减少到 100ms）
delay = 100
# 是否在启动时重新构建
stop_on_error = false
# 发生错误时是否发送通知
send_interrupt = false
# 终止信号
kill_delay = "5s"
# 日志格式
log = "time"
# 颜色
color = true
# 启用轮询模式
poll = true
poll_interval = 500

[log]
# 显示日志时间
time = true

[color]
# 自定义颜色
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[screen]
clear_on_rebuild = true

[misc]
# 当遇到错误时清理旧的二进制文件
clean_on_exit = true 