version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=daily_report
      - DB_PASSWORD=daily_report_password
      - DB_NAME=daily_report
      - DB_CHARSET=utf8mb4
      - DB_LOC=Local
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: cached
      - type: bind
        source: ./tmp
        target: /app/tmp
        consistency: cached
      - go-mod-cache:/go/pkg/mod
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - daily-report-net

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=daily_report
      - MYSQL_USER=daily_report
      - MYSQL_PASSWORD=daily_report_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "daily_report", "-pdaily_report_password"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - daily-report-net

networks:
  daily-report-net:
    driver: bridge

volumes:
  mysql_data:
  go-mod-cache: 