database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  name: daily_report
  charset: utf8mb4
  parseTime: true
  loc: Local

server:
  port: 8080
  mode: debug  # debug or release 