database:
  driver: mysql
  host: mysql
  port: 3306
  username: daily_report
  password: daily_report_password
  name: daily_report
  charset: utf8mb4
  parseTime: true
  loc: Local

server:
  port: 8080
  mode: release  # 设置为生产模式

jwt:
  secret: "your-super-secret-key-please-change-in-production"  # 请在生产环境中修改此密钥 

logging:
  level: info
  format: json
  output: stdout 